<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="11922" started-at="2018-06-08T10:03:00Z" finished-at="2018-06-08T10:03:12Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="11922" started-at="2018-06-08T10:03:00Z" finished-at="2018-06-08T10:03:12Z">
      <class name="tests.TestApp">
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:tests.TestApp@5a39699c]" name="beforeTest" is-config="true" duration-ms="47" started-at="2018-06-08T05:03:04Z" finished-at="2018-06-08T05:03:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testMercuryTours()[pri:0, instance:tests.TestApp@5a39699c]" name="testMercuryTours" duration-ms="6834" started-at="2018-06-08T05:03:04Z" finished-at="2018-06-08T05:03:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Intentionally failed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Intentionally failed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at pages.MercuryToursRegisterPage.clickSignOff(MercuryToursRegisterPage.java:30)
	at tests.TestApp.testMercuryTours(TestApp.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMercuryTours -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:tests.TestApp@5a39699c]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-06-08T05:03:12Z" finished-at="2018-06-08T05:03:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- tests.TestApp -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
